version: '3'
services:
  account-service:
    image: account-service
    build:
      context: ./account-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CUSTOMER_SERVICE_URL: http://customer-service:8081/api/v1/customers/

  customer-service:
    image: customer-service
    build:
      context: ./customer-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  transaction-service:
    image: transaction-service
    build:
      context: ./transaction-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      ACCOUNT_SERVICE_URL: http://account-service:8080/api/v1/accounts
    depends_on:
      - account-service
      - customer-service

